/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/deps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe - checks backing services */
        get: operations["health_deps_health_deps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new account */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description OAuth2 password flow.
         *
         *     The form field is named ``username`` by the OAuth2 spec; we treat it as the
         *     email address. Using the standard form is what lets Swagger UI's Authorize
         *     button work directly against this endpoint.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my meetings
         * @description Only the caller's own meetings. The owner filter is not optional.
         */
        get: operations["list_meetings_api_v1_meetings_get"];
        put?: never;
        /** Create a meeting */
        post: operations["create_meeting_api_v1_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one meeting */
        get: operations["get_meeting_api_v1_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Delete a meeting */
        delete: operations["delete_meeting_api_v1_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /** Update a meeting */
        patch: operations["update_meeting_api_v1_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the meeting transcript */
        get: operations["get_transcript_api_v1_meetings__meeting_id__transcript_get"];
        /**
         * Add or replace the meeting transcript
         * @description PUT, not POST: a meeting has exactly one transcript, and sending the same
         *     body twice leaves the same state (idempotent).
         */
        put: operations["upsert_transcript_api_v1_meetings__meeting_id__transcript_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue AI extraction of summary, decisions, and action items
         * @description Returns immediately. Poll ``GET /api/v1/jobs/{job_id}`` for the outcome.
         *
         *     Submitting again while a job for this meeting is still queued or running
         *     returns that same job rather than starting a duplicate.
         */
        post: operations["process_api_v1_meetings__meeting_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/intelligence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary, participants, decisions, and action items in one response */
        get: operations["get_intelligence_api_v1_meetings__meeting_id__intelligence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the AI summary */
        get: operations["get_summary_api_v1_meetings__meeting_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions from this meeting */
        get: operations["list_meeting_decisions_api_v1_meetings__meeting_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Action items from this meeting */
        get: operations["list_meeting_action_items_api_v1_meetings__meeting_id__action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People named in this meeting */
        get: operations["list_participants_api_v1_meetings__meeting_id__participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my action items across all meetings */
        get: operations["list_action_items_api_v1_action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-items/{action_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update or correct an action item */
        patch: operations["update_action_item_api_v1_action_items__action_item_id__patch"];
        trace?: never;
    };
    "/api/v1/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update or correct a decision */
        patch: operations["update_decision_api_v1_decisions__decision_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a processing job
         * @description Poll this after POST /process until ``status`` is COMPLETED or FAILED.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing history for a meeting, newest first */
        get: operations["list_meeting_jobs_api_v1_meetings__meeting_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/media/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a direct upload URL */
        post: operations["create_upload_url_api_v1_meetings__meeting_id__media_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/media/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an upload and queue transcription + processing */
        post: operations["complete_upload_api_v1_meetings__meeting_id__media_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the recording, with a playback URL */
        get: operations["get_media_api_v1_meetings__meeting_id__media_get"];
        put?: never;
        post?: never;
        /**
         * Delete the recording
         * @description Removes the recording. A transcript already produced from it is kept.
         */
        delete: operations["delete_media_api_v1_meetings__meeting_id__media_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts, recent meetings, and items needing attention */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find transcript passages by meaning, not just matching words
         * @description Results are ordered by cosine similarity (``score``, higher is closer).
         *
         *     Only meetings the user can access are searched, and only chunks built from
         *     the meeting's current transcript. A meeting becomes searchable once it has
         *     been processed.
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The structured Minutes of Meeting
         * @description Assembled from the stored results, including the user's corrections, so it
         *     always matches what the PDF shows.
         */
        get: operations["get_minutes_api_v1_meetings__meeting_id__mom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/mom/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate (or reuse) the Minutes of Meeting PDF and get view/download links
         * @description The PDF is stored in object storage. An identical stored PDF is reused;
         *     if the minutes changed since it was made, a new one is rendered first.
         *
         *     Links are short-lived presigned URLs: ``view_url`` opens in the browser,
         *     ``download_url`` saves the file.
         */
        post: operations["minutes_pdf_api_v1_meetings__meeting_id__mom_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer a question from your meetings, with cited sources
         * @description Searches the transcripts and Minutes of Meeting of the meetings you can
         *     access, and answers **only** from what it finds.
         *
         *     * ``answered``: every statement cites a numbered source, and ``sources``
         *       lists exactly the cited passages with their meeting.
         *     * ``insufficient_context``: nothing relevant was found, or the model could
         *       not support an answer from what was found. Nothing is invented.
         *     * ``no_indexed_meetings``: no processed meetings to search yet.
         */
        post: operations["ask_meetings_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemCounts */
        ActionItemCounts: {
            /** Open */
            open: number;
            /** Overdue */
            overdue: number;
            /** Due Soon */
            due_soon: number;
            /** Done */
            done: number;
        };
        /**
         * ActionItemPriority
         * @enum {string}
         */
        ActionItemPriority: "low" | "medium" | "high";
        /** ActionItemResponse */
        ActionItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Position */
            position: number;
            /** Task */
            task: string;
            /** Owner Name */
            owner_name: string | null;
            /** Owner Participant Id */
            owner_participant_id: string | null;
            /** Deadline */
            deadline: string | null;
            /** Deadline Text */
            deadline_text: string | null;
            priority: components["schemas"]["ActionItemPriority"] | null;
            status: components["schemas"]["ActionItemStatus"];
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Evidence Verified */
            evidence_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Meeting Title */
            meeting_title?: string | null;
            /** Is Overdue */
            readonly is_overdue: boolean;
        };
        /**
         * ActionItemStatus
         * @enum {string}
         */
        ActionItemStatus: "pending" | "in_progress" | "done" | "cancelled";
        /**
         * ActionItemUpdateRequest
         * @description Human corrections to an extracted action item. Every field optional.
         *
         *     ``deadline`` and ``priority`` may be set to null deliberately (to clear
         *     them); ``task`` and ``status`` may not.
         */
        ActionItemUpdateRequest: {
            /** Task */
            task?: string | null;
            status?: components["schemas"]["ActionItemStatus"] | null;
            /** Deadline */
            deadline?: string | null;
            priority?: components["schemas"]["ActionItemPriority"] | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Meeting Ids
             * @description Only search these meetings (each must be accessible). Default: all.
             */
            meeting_ids?: string[] | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Question */
            question: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "insufficient_context" | "no_indexed_meetings";
            /** Answer */
            answer: string;
            /**
             * Sources
             * @description Only the sources the answer cites.
             */
            sources: components["schemas"]["AskSource"][];
            /**
             * Retrieved
             * @description Passages retrieved and shown to the model.
             */
            retrieved: number;
            /**
             * Model
             * @description The answering model; null if it was not called.
             */
            model: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** AskSource */
        AskSource: {
            /**
             * Number
             * @description The [n] used in the answer.
             */
            number: number;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Meeting Title */
            meeting_title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            kind: components["schemas"]["ChunkSource"];
            /**
             * Text
             * @description What the model was shown for this source.
             */
            text: string;
            /**
             * Char Start
             * @description Transcript offsets, for transcript sources.
             */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Score */
            score: number;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * ChunkSource
         * @description What a chunk was built from (M8).
         *
         *     ``transcript`` passages are exact slices of the transcript (M6). The others
         *     are embedded from the meeting's Minutes of Meeting so questions about
         *     decisions, owners, and open items retrieve the structured answer, not only
         *     the conversation around it.
         * @enum {string}
         */
        ChunkSource: "transcript" | "summary" | "decision" | "action_item" | "pending" | "next_steps";
        /** DashboardResponse */
        DashboardResponse: {
            meetings: components["schemas"]["MeetingCounts"];
            action_items: components["schemas"]["ActionItemCounts"];
            /** Recent Meetings */
            recent_meetings: components["schemas"]["MeetingResponse"][];
            /** Attention */
            attention: components["schemas"]["ActionItemResponse"][];
        };
        /** DecisionResponse */
        DecisionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Position */
            position: number;
            /** Decision Text */
            decision_text: string;
            /** Context */
            context: string | null;
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Evidence Verified */
            evidence_verified: boolean;
            status: components["schemas"]["DecisionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DecisionStatus
         * @enum {string}
         */
        DecisionStatus: "open" | "resolved" | "superseded";
        /** DecisionUpdateRequest */
        DecisionUpdateRequest: {
            status?: components["schemas"]["DecisionStatus"] | null;
            /** Decision Text */
            decision_text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** JobEvent */
        JobEvent: {
            /** At */
            at: string;
            /**
             * Type
             * @description queued, started, transcription_started, transcription_completed, indexing_completed, mom_pdf_generated, mom_pdf_failed, retry_scheduled, lease_expired_requeued, completed, failed
             */
            type: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            status: components["schemas"]["JobStatus"];
            /** Force */
            force: boolean;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Next Attempt At
             * @description When a QUEUED job becomes runnable (later than now after a failed attempt).
             */
            next_attempt_at: string | null;
            /** @description For FAILED jobs, the final error. For a QUEUED job that already failed once, the error that caused the retry. */
            error: components["schemas"]["JobError"] | null;
            result: components["schemas"]["JobResult"] | null;
            /** Events */
            events: components["schemas"]["JobEvent"][];
        };
        /** JobResult */
        JobResult: {
            /** Cached */
            cached: boolean;
            /**
             * Transcribed
             * @default false
             */
            transcribed: boolean;
            /** Chunks */
            chunks?: number | null;
            /** Minutes Chunks */
            minutes_chunks?: number | null;
            /** Mom Pdf */
            mom_pdf?: boolean | null;
            /** Decisions */
            decisions: number;
            /** Action Items */
            action_items: number;
            /** Participants */
            participants: number;
            /** Warnings */
            warnings: string[];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "QUEUED" | "PROCESSING" | "COMPLETED" | "FAILED";
        /** MediaResponse */
        MediaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Original Filename */
            original_filename: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Download Url
             * @description Short-lived presigned URL for playback.
             */
            download_url?: string | null;
        };
        /** MeetingCounts */
        MeetingCounts: {
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
        };
        /** MeetingCreateRequest */
        MeetingCreateRequest: {
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** Description */
            description?: string | null;
            /** @default text */
            source_type: components["schemas"]["MeetingSourceType"];
        };
        /** MeetingIntelligenceResponse */
        MeetingIntelligenceResponse: {
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            status: components["schemas"]["MeetingStatus"];
            /**
             * Cached
             * @description True when the stored result was current and no LLM call was made.
             */
            cached: boolean;
            /** Warnings */
            warnings: string[];
            summary: components["schemas"]["SummaryResponse"] | null;
            /** Participants */
            participants: components["schemas"]["ParticipantResponse"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionResponse"][];
            /** Action Items */
            action_items: components["schemas"]["ActionItemResponse"][];
        };
        /** MeetingResponse */
        MeetingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            source_type: components["schemas"]["MeetingSourceType"];
            status: components["schemas"]["MeetingStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MeetingSourceType
         * @description How the meeting content arrived.
         * @enum {string}
         */
        MeetingSourceType: "text" | "audio" | "video";
        /**
         * MeetingStatus
         * @description Lifecycle of the AI processing pipeline.
         * @enum {string}
         */
        MeetingStatus: "created" | "queued" | "processing" | "completed" | "failed";
        /**
         * MeetingUpdateRequest
         * @description Partial update - every field optional.
         *
         *     Distinguishing "field absent" from "field set to null" is done with
         *     ``model_dump(exclude_unset=True)`` in the route, so PATCH with an empty
         *     body is a no-op rather than wiping the record.
         */
        MeetingUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Meeting Date */
            meeting_date?: string | null;
            /** Description */
            description?: string | null;
            source_type?: components["schemas"]["MeetingSourceType"] | null;
        };
        /** MinutesOfMeeting */
        MinutesOfMeeting: {
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Title */
            title: string;
            /**
             * Agenda
             * @description The meeting description / agenda, as entered.
             */
            agenda: string | null;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** Participants */
            participants: string[];
            /** Speakers */
            speakers: components["schemas"]["MomSpeaker"][];
            /** Executive Summary */
            executive_summary: string;
            /** Key Points */
            key_points: string[];
            /** Keywords */
            keywords: string[];
            /** Decisions */
            decisions: components["schemas"]["MomDecision"][];
            /** Action Items */
            action_items: components["schemas"]["MomActionItem"][];
            /** Pending Items */
            pending_items: components["schemas"]["MomPendingItem"][];
            /** Next Steps */
            next_steps: string[];
            /**
             * Next Steps Derived
             * @description True when no next steps were stated and they were derived from open action items.
             */
            next_steps_derived: boolean;
            /** Review Flags */
            review_flags: components["schemas"]["MomReviewFlag"][];
            source: components["schemas"]["MomSource"];
            /**
             * Is Stale
             * @description The transcript changed after these minutes were extracted.
             */
            is_stale: boolean;
        };
        /** MomActionItem */
        MomActionItem: {
            /** Number */
            number: number;
            /** Task */
            task: string;
            /** Owner */
            owner: string | null;
            /** Deadline */
            deadline: string | null;
            /** Deadline Text */
            deadline_text: string | null;
            priority: components["schemas"]["ActionItemPriority"] | null;
            status: components["schemas"]["ActionItemStatus"];
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Evidence Verified */
            evidence_verified: boolean;
        };
        /** MomDecision */
        MomDecision: {
            /** Number */
            number: number;
            /** Text */
            text: string;
            /** Context */
            context: string | null;
            status: components["schemas"]["DecisionStatus"];
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Evidence Verified */
            evidence_verified: boolean;
        };
        /** MomPdfResponse */
        MomPdfResponse: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Pages
             * @description Known when this request rendered the document.
             */
            pages: number | null;
            /**
             * Fingerprint
             * @description Hash of the minutes content the PDF was rendered from.
             */
            fingerprint: string;
            /**
             * Reused
             * @description True when an identical stored PDF was reused.
             */
            reused: boolean;
            /**
             * View Url
             * @description Opens the PDF in the browser. Short-lived.
             */
            view_url: string;
            /**
             * Download Url
             * @description Downloads the PDF. Short-lived.
             */
            download_url: string;
            /** Expires In */
            expires_in: number;
        };
        /** MomPendingItem */
        MomPendingItem: {
            /** Item */
            item: string;
            /** Evidence Quote */
            evidence_quote: string | null;
            /** Evidence Verified */
            evidence_verified: boolean;
        };
        /**
         * MomReviewFlag
         * @description Something a person should check before relying on the minutes.
         *
         *     Produced by deterministic validation, not by the model.
         */
        MomReviewFlag: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "missing_owner" | "missing_deadline" | "unresolved_deadline" | "unverified_evidence" | "unnamed_speakers" | "stale_transcript";
            /** Message */
            message: string;
        };
        /** MomSource */
        MomSource: {
            /**
             * Input Kind
             * @enum {string}
             */
            input_kind: "transcript" | "notes" | "recording";
            /** Transcript Words */
            transcript_words: number;
            /** Transcript Sha256 */
            transcript_sha256: string;
            /** Language */
            language: string | null;
            /** Recording Filename */
            recording_filename: string | null;
            /** Recording Type */
            recording_type: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Transcription Model */
            transcription_model: string | null;
            /** Extraction Provider */
            extraction_provider: string;
            /** Extraction Model */
            extraction_model: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /**
             * Evidence Verified
             * @description Items whose evidence quote was found in the input.
             */
            evidence_verified: number;
            /**
             * Evidence Total
             * @description Items that carry an evidence quote requirement.
             */
            evidence_total: number;
        };
        /** MomSpeaker */
        MomSpeaker: {
            /** Name */
            name: string;
            /** Contribution */
            contribution: string | null;
            /**
             * Turns
             * @description Speaking turns counted from the transcript (0 for notes).
             */
            turns: number;
            /** Words */
            words: number;
            /**
             * Share
             * @description Share of all spoken words, 0 to 1.
             */
            share: number;
        };
        /** Page[ActionItemResponse] */
        Page_ActionItemResponse_: {
            /** Items */
            items: components["schemas"]["ActionItemResponse"][];
            /**
             * Total
             * @description Total rows matching the filter, ignoring pagination.
             */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[MeetingResponse] */
        Page_MeetingResponse_: {
            /** Items */
            items: components["schemas"]["MeetingResponse"][];
            /**
             * Total
             * @description Total rows matching the filter, ignoring pagination.
             */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** ParticipantResponse */
        ParticipantResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** User Id */
            user_id: string | null;
        };
        /**
         * ProcessSubmissionResponse
         * @description Response to POST /meetings/{id}/process.
         *
         *     * 202 with ``job`` set: work was queued (or an identical job was already
         *       active and is returned instead of starting a duplicate).
         *     * 200 with ``job`` null and ``cached`` true: stored results are already
         *       current for this transcript, prompt, and model. Nothing was queued.
         */
        ProcessSubmissionResponse: {
            /** Cached */
            cached: boolean;
            meeting_status: components["schemas"]["MeetingStatus"];
            job: components["schemas"]["JobResponse"] | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Model */
            model: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Meeting Title */
            meeting_title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Score */
            score: number;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Summary Text */
            summary_text: string;
            /** Key Points */
            key_points: string[];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Stale
             * @description True when the transcript has changed since this summary was generated.
             * @default false
             */
            is_stale: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TranscriptResponse */
        TranscriptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /** Content */
            content: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Char Count */
            char_count: number;
            /** Word Count */
            word_count: number;
            /** Language */
            language: string | null;
            source: components["schemas"]["TranscriptSource"];
            /** Media Id */
            media_id: string | null;
            /** Transcription Model */
            transcription_model: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TranscriptSource
         * @enum {string}
         */
        TranscriptSource: "manual" | "transcription" | "notes";
        /** TranscriptUpsertRequest */
        TranscriptUpsertRequest: {
            /**
             * Content
             * @description Plain-text transcript. Speaker labels such as 'Priya:' improve owner extraction.
             */
            content: string;
            /**
             * Language
             * @example en
             */
            language?: string | null;
            /**
             * Kind
             * @description 'transcript' for verbatim speech, 'notes' for meeting notes or a written description. The AI is told which it is reading.
             * @default transcript
             * @enum {string}
             */
            kind: "transcript" | "notes";
        };
        /** UploadCompleteRequest */
        UploadCompleteRequest: {
            /** Upload Token */
            upload_token: string;
            /**
             * Replace Manual Transcript
             * @description A typed/pasted transcript normally takes precedence over a recording. Set true to discard it and transcribe the recording instead.
             * @default false
             */
            replace_manual_transcript: boolean;
        };
        /** UploadCompleteResponse */
        UploadCompleteResponse: {
            media: components["schemas"]["MediaResponse"];
            job: components["schemas"]["JobResponse"];
        };
        /** UploadUrlRequest */
        UploadUrlRequest: {
            /**
             * Filename
             * @example standup-2026-09-10.m4a
             */
            filename: string;
            /**
             * Content Type
             * @example audio/mp4
             */
            content_type: string;
            /**
             * Size Bytes
             * @description Checked early for a friendly error; storage enforces the real limit.
             */
            size_bytes: number;
        };
        /**
         * UploadUrlResponse
         * @description Everything the browser needs to upload directly to storage.
         *
         *     Send a multipart/form-data POST to ``upload_url`` containing every entry in
         *     ``fields`` followed by the file under the name ``file``. Then call
         *     ``POST /meetings/{id}/media/complete`` with ``upload_token``.
         */
        UploadUrlResponse: {
            /** Upload Url */
            upload_url: string;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Upload Token */
            upload_token: string;
            /** Expires In */
            expires_in: number;
            /** Max Bytes */
            max_bytes: number;
        };
        /** UserRegisterRequest */
        UserRegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * UserResponse
         * @description Public view of a user. Deliberately has no password_hash field.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_deps_health_deps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_meetings_api_v1_meetings_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["MeetingStatus"] | null;
                /** @description Case-insensitive search in title and description. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MeetingResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_v1_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_v1_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_v1_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_api_v1_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_v1_meetings__meeting_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_transcript_api_v1_meetings__meeting_id__transcript_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_api_v1_meetings__meeting_id__process_post: {
        parameters: {
            query?: {
                /** @description Re-run even if the stored result is current. Replaces previous results, including manual status changes on action items. */
                force?: boolean;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored results are already current; nothing was queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessSubmissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intelligence_api_v1_meetings__meeting_id__intelligence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingIntelligenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_meetings__meeting_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meeting_decisions_api_v1_meetings__meeting_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meeting_action_items_api_v1_meetings__meeting_id__action_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_v1_meetings__meeting_id__participants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_action_items_api_v1_action_items_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ActionItemStatus"] | null;
                /** @description Only open items whose deadline has passed. */
                overdue?: boolean;
                meeting_id?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActionItemResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_action_item_api_v1_action_items__action_item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_decision_api_v1_decisions__decision_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meeting_jobs_api_v1_meetings__meeting_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_api_v1_meetings__meeting_id__media_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_meetings__meeting_id__media_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_api_v1_meetings__meeting_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_api_v1_meetings__meeting_id__media_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                /** @description Search one meeting only */
                meeting_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_minutes_api_v1_meetings__meeting_id__mom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesOfMeeting"];
                };
            };
            /** @description The meeting has not been processed yet (minutes_not_ready). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    minutes_pdf_api_v1_meetings__meeting_id__mom_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomPdfResponse"];
                };
            };
            /** @description The meeting has not been processed yet (minutes_not_ready). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_meetings_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
