"""add users and meetings

Also enables the pgvector extension. Nothing in M1 stores a vector, but
enabling it here proves the extension is available on this PostgreSQL server
and makes the M6 embedding work a pure schema addition rather than a
dependency gamble discovered late.

Revision ID: 0001
Revises:
Create Date: 2026-09-12 22:42:14.075941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector: required from M6 onward for meeting_chunks.embedding.
    # IF NOT EXISTS keeps the migration idempotent and safe to re-run.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "meetings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("meeting_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "text", "audio", "video", name="meeting_source_type", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "processing",
                "completed",
                "failed",
                name="meeting_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_meetings_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_index(op.f("ix_meetings_owner_id"), "meetings", ["owner_id"], unique=False)
    op.create_index(
        "ix_meetings_owner_id_meeting_date",
        "meetings",
        ["owner_id", sa.literal_column("meeting_date DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_meetings_status"), "meetings", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meetings_status"), table_name="meetings")
    op.drop_index("ix_meetings_owner_id_meeting_date", table_name="meetings")
    op.drop_index(op.f("ix_meetings_owner_id"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # The extension is intentionally NOT dropped: other databases or
    # schemas on the same server may rely on it.
    # ### end Alembic commands ###
