"""add meeting media and transcript provenance

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-13 23:10:48.998214

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_media",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("etag", sa.String(length=128), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_media_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_media")),
        sa.UniqueConstraint("meeting_id", name=op.f("uq_meeting_media_meeting_id")),
    )
    op.add_column("transcripts", sa.Column("media_id", sa.Uuid(), nullable=True))
    op.add_column("transcripts", sa.Column("media_etag", sa.String(length=128), nullable=True))
    op.add_column("transcripts", sa.Column("raw_s3_key", sa.String(length=512), nullable=True))
    op.add_column(
        "transcripts", sa.Column("transcription_model", sa.String(length=100), nullable=True)
    )
    op.add_column("transcripts", sa.Column("duration_seconds", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_transcripts_media_id_meeting_media"),
        "transcripts",
        "meeting_media",
        ["media_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcripts_media_id_meeting_media"), "transcripts", type_="foreignkey"
    )
    op.drop_column("transcripts", "duration_seconds")
    op.drop_column("transcripts", "transcription_model")
    op.drop_column("transcripts", "raw_s3_key")
    op.drop_column("transcripts", "media_etag")
    op.drop_column("transcripts", "media_id")
    op.drop_table("meeting_media")
    # ### end Alembic commands ###
