"""agent runs and follow-up proposals

The follow-up agent (ADR 0015): its run log with a per-run step trace, and the
proposals it makes for a person to approve or reject. One running run per user
is enforced by a partial unique index; a proposal is never made twice for the
same dedupe key.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-18 15:33:43.900870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="agent_run_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("candidates_found", sa.Integer(), nullable=False),
        sa.Column("proposals_created", sa.Integer(), nullable=False),
        sa.Column("used_fallback", sa.Boolean(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_agent_runs_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        "ix_agent_runs_owner_id_started_at", "agent_runs", ["owner_id", "started_at"], unique=False
    )
    op.create_index(
        "uq_agent_runs_one_running_per_owner",
        "agent_runs",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "follow_up_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("action_item_id", sa.Uuid(), nullable=True),
        sa.Column("decision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "overdue_action",
                "due_soon_action",
                "unassigned_action",
                "open_decision",
                "unresolved_topic",
                "recurring_topic",
                name="proposal_kind",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="proposal_priority",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("draft_subject", sa.String(length=300), nullable=False),
        sa.Column("draft_body", sa.Text(), nullable=False),
        sa.Column(
            "drafted_by",
            sa.Enum(
                "ai",
                "template",
                name="draft_source",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "rejected",
                name="proposal_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("final_subject", sa.String(length=300), nullable=True),
        sa.Column("final_body", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_item_id"],
            ["action_items.id"],
            name=op.f("fk_follow_up_proposals_action_item_id_action_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
            name=op.f("fk_follow_up_proposals_decision_id_decisions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_follow_up_proposals_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_follow_up_proposals_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_follow_up_proposals_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_up_proposals")),
        sa.UniqueConstraint(
            "owner_id", "dedupe_key", name="uq_follow_up_proposals_owner_id_dedupe_key"
        ),
    )
    op.create_index(
        op.f("ix_follow_up_proposals_meeting_id"),
        "follow_up_proposals",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        "ix_follow_up_proposals_owner_id_status",
        "follow_up_proposals",
        ["owner_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_follow_up_proposals_owner_id_status", table_name="follow_up_proposals")
    op.drop_index(op.f("ix_follow_up_proposals_meeting_id"), table_name="follow_up_proposals")
    op.drop_table("follow_up_proposals")
    op.drop_index(
        "uq_agent_runs_one_running_per_owner",
        table_name="agent_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_agent_runs_owner_id_started_at", table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
